services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: biolid-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./data/mosquitto/config:/mosquitto/config
      - ./data/mosquitto/data:/mosquitto/data
      - ./data/mosquitto/log:/mosquitto/log
    restart: unless-stopped
